//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMirror.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyMirror.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About EasyMirror.
        /// </summary>
        public static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyMirror.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyMirror encountered errors while mirroring. The following operations were not completed successfully due to access restrictions or read errors:.
        /// </summary>
        public static string BAD_OPERATIONS {
            get {
                return ResourceManager.GetString("BAD_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyMirror encountered errors while comparing. The following files and directories cannot be mirrored/updated due to access restrictions or read errors:.
        /// </summary>
        public static string BAD_PATHS {
            get {
                return ResourceManager.GetString("BAD_PATHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Per Mortensen, 2011-2012.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string COMPARE {
            get {
                return ResourceManager.GetString("COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination directories match..
        /// </summary>
        public static string COMPLETE_MATCH {
            get {
                return ResourceManager.GetString("COMPLETE_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary directory: .
        /// </summary>
        public static string DELETE_DIRECTORY {
            get {
                return ResourceManager.GetString("DELETE_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary file: .
        /// </summary>
        public static string DELETE_FILE {
            get {
                return ResourceManager.GetString("DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  directories to create.
        /// </summary>
        public static string DIRECTORIES_TO_CREATE {
            get {
                return ResourceManager.GetString("DIRECTORIES_TO_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  directories to delete.
        /// </summary>
        public static string DIRECTORIES_TO_DELETE {
            get {
                return ResourceManager.GetString("DIRECTORIES_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string DIRECTORY_SEPARATOR {
            get {
                return ResourceManager.GetString("DIRECTORY_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap easymirrorlogo {
            get {
                object obj = ResourceManager.GetObject("easymirrorlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error reported to EasyMirror was: .
        /// </summary>
        public static string EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  files to copy.
        /// </summary>
        public static string FILES_TO_COPY {
            get {
                return ResourceManager.GetString("FILES_TO_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  files to delete.
        /// </summary>
        public static string FILES_TO_DELETE {
            get {
                return ResourceManager.GetString("FILES_TO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  files to update.
        /// </summary>
        public static string FILES_TO_OVERWRITE {
            get {
                return ResourceManager.GetString("FILES_TO_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ICON_ARROW {
            get {
                object obj = ResourceManager.GetObject("ICON_ARROW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ICON_BROWSE {
            get {
                object obj = ResourceManager.GetObject("ICON_BROWSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ICON_CANCEL {
            get {
                object obj = ResourceManager.GetObject("ICON_CANCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ICON_COMPARE {
            get {
                object obj = ResourceManager.GetObject("ICON_COMPARE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ICON_MIRROR {
            get {
                object obj = ResourceManager.GetObject("ICON_MIRROR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons from.
        /// </summary>
        public static string ICONS_FROM {
            get {
                return ResourceManager.GetString("ICONS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory:.
        /// </summary>
        public static string MASTER_DIRECTORY {
            get {
                return ResourceManager.GetString("MASTER_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination directories cannot contain each other. Please select a different directory..
        /// </summary>
        public static string MASTER_MIRROR_CONFLICT {
            get {
                return ResourceManager.GetString("MASTER_MIRROR_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string MIRROR {
            get {
                return ResourceManager.GetString("MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mirror operation was completed successfully..
        /// </summary>
        public static string MIRROR_COMPLETED {
            get {
                return ResourceManager.GetString("MIRROR_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory:.
        /// </summary>
        public static string MIRROR_DIRECTORY {
            get {
                return ResourceManager.GetString("MIRROR_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory: .
        /// </summary>
        public static string NEW_DIRECTORY {
            get {
                return ResourceManager.GetString("NEW_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file: .
        /// </summary>
        public static string NEW_FILE {
            get {
                return ResourceManager.GetString("NEW_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated file: .
        /// </summary>
        public static string OVERWRITE_FILE {
            get {
                return ResourceManager.GetString("OVERWRITE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyMirror encountered a path too long for the filesystem. Comparison cannot continue..
        /// </summary>
        public static string PATH_TOO_LONG {
            get {
                return ResourceManager.GetString("PATH_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing....
        /// </summary>
        public static string STATUS_COMPARING {
            get {
                return ResourceManager.GetString("STATUS_COMPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying .
        /// </summary>
        public static string STATUS_COPYING {
            get {
                return ResourceManager.GetString("STATUS_COPYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating .
        /// </summary>
        public static string STATUS_CREATING {
            get {
                return ResourceManager.GetString("STATUS_CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting .
        /// </summary>
        public static string STATUS_DELETING {
            get {
                return ResourceManager.GetString("STATUS_DELETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirroring....
        /// </summary>
        public static string STATUS_MIRRORING {
            get {
                return ResourceManager.GetString("STATUS_MIRRORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string STATUS_READY {
            get {
                return ResourceManager.GetString("STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating .
        /// </summary>
        public static string STATUS_UPDATING {
            get {
                return ResourceManager.GetString("STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are .
        /// </summary>
        public static string THERE_ARE {
            get {
                return ResourceManager.GetString("THERE_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string TOTAL_PROGRESS {
            get {
                return ResourceManager.GetString("TOTAL_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyMirror encountered a path for which you do not have access rights. Comparison cannot continue..
        /// </summary>
        public static string UNAUTHORIZED_ACCESS {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UNKNOWN_EXCEPTION {
            get {
                return ResourceManager.GetString("UNKNOWN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compare operation was cancelled..
        /// </summary>
        public static string USER_CANCELLED_COMPARE {
            get {
                return ResourceManager.GetString("USER_CANCELLED_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mirror operation was cancelled..
        /// </summary>
        public static string USER_CANCELLED_MIRROR {
            get {
                return ResourceManager.GetString("USER_CANCELLED_MIRROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.2.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version .
        /// </summary>
        public static string VERSION_TITLE {
            get {
                return ResourceManager.GetString("VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
